import { StyleSheet } from 'react-native';
import { normalize } from '@/utils/layout';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  content: { padding: normalize(20) },
  errorBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: normalize(8),
    borderWidth: 1,
    borderRadius: normalize(10),
    padding: normalize(12),
    marginBottom: normalize(16),
  },
  errorText: { fontSize: normalize(13), flex: 1 },
  inputGroup: { marginBottom: normalize(20) },
  label: { fontSize: normalize(14), marginBottom: normalize(8), fontWeight: "500" },
  badgeRow: { flexDirection: "row", gap: normalize(10) },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: normalize(6),
    paddingHorizontal: normalize(12),
    paddingVertical: normalize(8),
    borderRadius: normalize(20),
    borderWidth: 1,
  },
  badgeText: { fontSize: normalize(13), fontWeight: "500" },
  row: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: normalize(12),
    borderWidth: 1,
    paddingHorizontal: normalize(16),
    height: normalize(56),
    gap: normalize(12),
  },
  rowText: { fontSize: normalize(15), flex: 1 },
  accountIcon: {
    width: normalize(32),
    height: normalize(32),
    borderRadius: normalize(16),
    alignItems: "center",
    justifyContent: "center",
  },
  toggleContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: normalize(24),
    marginTop: normalize(4),
  },
  toggleLabel: { fontSize: normalize(15), flex: 1, paddingRight: normalize(16) },
  progressContainer: {
    borderWidth: 1,
    borderRadius: normalize(12),
    padding: normalize(14),
    gap: normalize(12),
    marginBottom: normalize(16),
  },
  progressItem: { gap: normalize(6) },
  progressLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: normalize(6),
  },
  progressFileName: { fontSize: normalize(13), flex: 1 },
  progressPct: { fontSize: normalize(12), fontWeight: "500" },
  progressTrack: {
    height: normalize(4),
    borderRadius: normalize(2),
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: normalize(2),
  },
  exportButton: {
    borderRadius: normalize(12),
    padding: normalize(16),
    alignItems: "center",
    marginTop: normalize(8),
  },
  exportButtonDisabled: { opacity: 0.45 },
  exportButtonText: { color: "#fff", fontSize: normalize(16), fontWeight: "600" },
});
