export const COMMAND_NAME = {
    SimpleSearchLoginDeviceInformation: "SimpleSearchLoginDeviceInformation",
    viewqrmerchantinfo: "viewqrmerchantinfo",
    viewbankinfo: "viewbankinfo",
    viewTermCondition: "viewtermcondition",
    getuserbyphonenumber: "getuserbyphonenumber",
    GetWalletStatement: "GetWalletStatement",
    SimpleSearchCountry:"SimpleSearchCountry",
    SimpleSearchRegion:"SimpleSearchRegion",
    SimpleSearchTownership:"SimpleSearchTownership",
    GetLanguagesVersion: "GetLanguagesVersion",
    UpdateIsBiometricSupported: "UpdateIsBiometricSupported",
    GetLoanProduct: "GetLoanProduct",
    GetSavingProduct: "GetSavingProduct",
    getTemplace: "getTemplace",
    saveTemplace: "saveTemplace",
    GetCountsUnreadNoti: "GetCountsUnreadNoti",
    GetNotificationDetail: "GetNotificationDetail",
    getuserbyusernameandphonenumber: "getuserbyusernameandphonenumber",
    getPhoneByUserName: "getPhoneByUserName",
    getPhoneByUserCode: "getPhoneByUserCode",
    getUserInfor: "getUserInfor",
    SimpleSearchSMSProvider: "SimpleSearchSMSProvider",
    SearchBannerByTypeUsingAndPosion: "SearchBannerByTypeUsingAndPosion",
    SimpleSearchCity: "SimpleSearchCity",
    SimpleSearchCityOption:"SimpleSearchCityOption",
    SimpleSearchDistrictOption:"SimpleSearchDistrictOption",
    SimpleSearchVillageOption:"SimpleSearchVillageOption",
    getLicenseIdAndTypeByContract: "getLicenseIdAndTypeByContract",
}