export default {
  TOKEN: 'user_token',
  USER_DATA: 'user_data',
  userCode: "userCode",
  defaultWalletId: "defaultWalletId",
  defaultCurrency: 'defaultCurrency',


  roleCommand: "rolecommand",
  password: "password",
  token: "token",
  user: "user",
  userSession: "usersession",
  refreshToken:"refresh_token",
  cacheCodeList: "cacheCodeList",
  cacheUserCommand: "cacheUserCommand",
  cacheParaServer: "cacheParaServer",
  commandMenu: "commandmenu",
  useBiometric: "is_biometric_supported",
  ListF8Transaction: "ListF8Transaction",
  appInfo: "appInfo",
  isVerifyFirstLogin: "isVerifyFirstLogin",
  baseURL: "baseURL",
  channelId: "channelId",
  AuthenticationMethod: "AuthenticationMethod",
  PopupBanners: "PopupBanners",
  ThemeBanners: "ThemeBanners",
  SelectedThemeBackground: "SelectedThemeBackground",
  HeaderBackground: "HeaderBackground",
  FestivalOverlayEnabled: "FestivalOverlayEnabled",
};
