import { StyleSheet } from "react-native";
import { Fonts } from "@/core/theme/font";
import { hp, normalize, wp } from "@/utils/layout";

export const createStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    flex: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      paddingBottom: hp(15),
    },
    section: {
      paddingHorizontal: wp(4),
      marginTop: hp(2),
    },
    label: {
      fontSize: normalize(14),
      color: colors.text,
      marginBottom: hp(1),
      fontFamily: Fonts.medium,
    },
    field: {
      backgroundColor: colors.card,
      borderRadius: normalize(12),
      padding: normalize(16),
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderColor: colors.border,
    },
    fieldLeft: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
    },
    fieldText: {
      fontSize: normalize(15),
      color: colors.text,
      marginLeft: wp(3),
      fontFamily: Fonts.regular,
    },
    categoryIcon: {
      width: normalize(40),
      height: normalize(40),
      borderRadius: normalize(10),
      alignItems: "center",
      justifyContent: "center",
    },
    amountContainer: {
      backgroundColor: colors.card,
      borderRadius: normalize(12),
      padding: normalize(16),
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    currency: {
      fontSize: normalize(16),
      color: colors.tint,
      fontFamily: Fonts.semiBold,
      marginRight: wp(2),
    },
    amountInput: {
      flex: 1,
      fontSize: normalize(18),
      color: colors.text,
      fontFamily: Fonts.regular,
    },
    datePicker: {
      backgroundColor: colors.card,
      borderRadius: normalize(12),
      padding: normalize(16),
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderColor: colors.border,
    },
    dateText: {
      fontSize: normalize(15),
      color: colors.text,
      fontFamily: Fonts.medium,
    },
    noteInput: {
      backgroundColor: colors.card,
      borderRadius: normalize(12),
      padding: normalize(16),
      borderWidth: 1,
      borderColor: colors.border,
      color: colors.text,
      fontSize: normalize(15),
      fontFamily: Fonts.regular,
      minHeight: hp(10),
    },
    infoBox: {
      marginHorizontal: wp(4),
      marginTop: hp(2),
      backgroundColor: colors.tint + "15",
      borderRadius: normalize(12),
      padding: normalize(16),
      flexDirection: "row",
      gap: normalize(12),
      borderWidth: 1,
      borderColor: colors.tint + "30",
    },
    infoTextContainer: {
      flex: 1,
    },
    infoText: {
      fontSize: normalize(13),
      color: colors.text,
      fontFamily: Fonts.regular,
      lineHeight: normalize(18),
    },
    bottomBar: {
      backgroundColor: colors.background,
      paddingHorizontal: wp(5),
      paddingTop: hp(1.5),
      borderTopWidth: 1,
      borderTopColor: colors.border,
      flexDirection: "row",
      gap: normalize(12),
    },
    cancelBtn: {
      flex: 1,
      paddingVertical: normalize(14),
      borderRadius: normalize(25),
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
    },
    cancelText: {
      fontSize: normalize(16),
      color: colors.tint,
      fontFamily: Fonts.semiBold,
    },
    createBtn: {
      flex: 1,
      paddingVertical: normalize(14),
      borderRadius: normalize(25),
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
      overflow: "hidden",
    },
    createText: {
      fontSize: normalize(16),
      color: "#fff",
      fontFamily: Fonts.semiBold,
    },
    deleteBtn: {
      flex: 1,
      paddingVertical: normalize(14),
      borderRadius: normalize(25),
      borderWidth: 1.5,
      borderColor: "#EF4444",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: wp(2),
    },
    deleteText: {
      fontSize: normalize(16),
      color: "#EF4444",
      fontFamily: Fonts.semiBold,
    },
    scanBtn: {
      width: normalize(40),
      height: normalize(40),
      alignItems: "center",
      justifyContent: "center",
    },
  });
