const fs = require('fs');
const path = require('path');

const ASSETS_PATH = path.join(__dirname, '../assets/IconInApp');
const OUTPUT_FILE = path.join(__dirname, '../src/utils/Icons.ts');

function toConstantName(str) {
    return str
        .toUpperCase()
        .replace(/, /g, '_')
        .replace(/ /g, '_')
        .replace(/[^\w]/g, '_') + '_ICONS';
}

function toIconKey(filename) {
    return filename
        .replace(/\.svg$/, '')
        .replace(/\.png$/, '')
        .toLowerCase()
        .replace(/ /g, '_')
        .replace(/-/g, '_')
        .replace(/[^\w]/g, '_');
}

function generateIcons() {
    console.log('--- Generating Icons Registry ---');
    
    if (!fs.existsSync(ASSETS_PATH)) {
        console.error('Assets path not found:', ASSETS_PATH);
        return;
    }

    const categories = fs.readdirSync(ASSETS_PATH).filter(f => 
        fs.statSync(path.join(ASSETS_PATH, f)).isDirectory()
    );

    let fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by scripts/generateIcons.js
 */

`;

    const allGroupNames = [];

    categories.forEach(cat => {
        const catPath = path.join(ASSETS_PATH, cat);
        const files = fs.readdirSync(catPath).filter(f => 
            f.endsWith('.svg') || f.endsWith('.png') || f.endsWith('.jpg')
        );

        if (files.length === 0) return;

        const constantName = toConstantName(cat);
        allGroupNames.push(constantName);

        fileContent += `// ${cat}\n`;
        fileContent += `export const ${constantName} = {\n`;

        const seenKeys = new Set();
        const catSlug = toIconKey(cat);

        files.forEach(file => {
            const fullPath = path.join(catPath, file);
            if (fs.statSync(fullPath).size === 0) {
                console.warn(`Skipping empty file: ${fullPath}`);
                return;
            }

            const namePart = toIconKey(file);
            let key = `${catSlug}_${namePart}`;
            
            // Handle internal duplicates within the same category
            let finalKey = key;
            let counter = 1;
            while (seenKeys.has(finalKey)) {
                finalKey = `${key}_${counter}`;
                counter++;
            }
            seenKeys.add(finalKey);

            // Use @assets alias for the require path
            const requirePath = `@assets/IconInApp/${cat}/${file}`;
            fileContent += `  '${finalKey}': require('${requirePath}'),\n`;
        });

        fileContent += `};\n\n`;
    });

    fileContent += `/**
 * Main registry for all local icons.
 * Usage: <AppIcon name="icon_key" />
 */
export const LOCAL_ICONS: Record<string, any> = {\n`;
    
    allGroupNames.forEach(name => {
        fileContent += `  ...${name},\n`;
    });
    
    fileContent += `};\n\n`;

    fileContent += `/**
 * Check if an icon name refers to a local asset
 */
export const isLocalIcon = (name: string): boolean => {
  return !!LOCAL_ICONS[name];
};\n`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`Successfully generated ${OUTPUT_FILE}`);
    console.log(`Total categories: ${allGroupNames.length}`);
}

generateIcons();
